### ISSUE TITLE
SelectInput - intl is not defined

### ISSUE THREAD

**Issue by mamico** [RedTurtle/design-comuni-plone-theme#252]
![image](https://github.com/RedTurtle/design-comuni-plone-theme/assets/182599/1e247aae-9730-400f-8175-7d9cdc8b78e3)

`intl` appears not to be defined here:

https://github.com/RedTurtle/design-comuni-plone-theme/blame/develop/src/components/SelectInput/SelectInput.jsx#L163

**Comment by pnicolli** [comment]
Fixed in version 8.0.3
